### PR TITLE
Sprint0 test pmdwight

### PR DESCRIPTION
**Pull request by pmdwight**
Have mercy!

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Payton, I'm loving the initiative bud, but the method already tells us this!

**Comment by pmdwight** [comment]
Let me pass!

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Loving the work bud, keep it up

**Comment by SatGarcia** [comment]
Don't forget to put "Resolves #X" in the description of your pull request so it automatically closes the associated issue.

**Pull request merged**
